/***** DO NOT EDIT THIS FILE *****/
// CountItOutProject.js generated by MonkeyTalk at 2013-01-03 14:04:51 PST

load("libs/MonkeyTalkAPI.js");


var CountItOutProject = {};

/*** script -- AnotherTest ***/
CountItOutProject.AnotherTest = function(app) {
	MT.Script.call(this, app, "AnotherTest.mt");
};

CountItOutProject.AnotherTest.prototype = new MT.Script;

CountItOutProject.AnotherTest.prototype.call = function() {
	//run: AnotherTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.anotherTest = function() {
	return new CountItOutProject.AnotherTest(this);
};

/*** script -- AwesomeTest ***/
CountItOutProject.AwesomeTest = function(app) {
	MT.Script.call(this, app, "AwesomeTest.mt");
};

CountItOutProject.AwesomeTest.prototype = new MT.Script;

CountItOutProject.AwesomeTest.prototype.call = function() {
	//run: AwesomeTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.awesomeTest = function() {
	return new CountItOutProject.AwesomeTest(this);
};

/*** script -- CountDownBasic ***/
CountItOutProject.CountDownBasic = function(app) {
	MT.Script.call(this, app, "CountDownBasic.mt");
};

CountItOutProject.CountDownBasic.prototype = new MT.Script;

CountItOutProject.CountDownBasic.prototype.call = function() {
	//run: CountDownBasic.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.countDownBasic = function() {
	return new CountItOutProject.CountDownBasic(this);
};

/*** script -- CountUpBasic ***/
CountItOutProject.CountUpBasic = function(app) {
	MT.Script.call(this, app, "CountUpBasic.mt");
};

CountItOutProject.CountUpBasic.prototype = new MT.Script;

CountItOutProject.CountUpBasic.prototype.call = function() {
	//run: CountUpBasic.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.countUpBasic = function() {
	return new CountItOutProject.CountUpBasic(this);
};

/*** script -- DecrementTest ***/
CountItOutProject.DecrementTest = function(app) {
	MT.Script.call(this, app, "DecrementTest.mt");
};

CountItOutProject.DecrementTest.prototype = new MT.Script;

CountItOutProject.DecrementTest.prototype.call = function() {
	//run: DecrementTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.decrementTest = function() {
	return new CountItOutProject.DecrementTest(this);
};

/*** script -- DeletesTest ***/
CountItOutProject.DeletesTest = function(app) {
	MT.Script.call(this, app, "DeletesTest.mt");
};

CountItOutProject.DeletesTest.prototype = new MT.Script;

CountItOutProject.DeletesTest.prototype.call = function() {
	//run: DeletesTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.deletesTest = function() {
	return new CountItOutProject.DeletesTest(this);
};

/*** script -- DualIncrementTest ***/
CountItOutProject.DualIncrementTest = function(app) {
	MT.Script.call(this, app, "DualIncrementTest.mt");
};

CountItOutProject.DualIncrementTest.prototype = new MT.Script;

CountItOutProject.DualIncrementTest.prototype.call = function() {
	//run: DualIncrementTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.dualIncrementTest = function() {
	return new CountItOutProject.DualIncrementTest(this);
};

/*** script -- FinalView ***/
CountItOutProject.FinalView = function(app) {
	MT.Script.call(this, app, "FinalView.mt");
};

CountItOutProject.FinalView.prototype = new MT.Script;

CountItOutProject.FinalView.prototype.call = function() {
	//run: FinalView.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.finalView = function() {
	return new CountItOutProject.FinalView(this);
};

/*** script -- IncTest ***/
CountItOutProject.IncTest = function(app) {
	MT.Script.call(this, app, "IncTest.mt");
};

CountItOutProject.IncTest.prototype = new MT.Script;

CountItOutProject.IncTest.prototype.call = function() {
	//run: IncTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.incTest = function() {
	return new CountItOutProject.IncTest(this);
};

/*** script -- InitialView ***/
CountItOutProject.InitialView = function(app) {
	MT.Script.call(this, app, "InitialView.mt");
};

CountItOutProject.InitialView.prototype = new MT.Script;

CountItOutProject.InitialView.prototype.call = function() {
	//run: InitialView.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.initialView = function() {
	return new CountItOutProject.InitialView(this);
};

/*** script -- PageView ***/
CountItOutProject.PageView = function(app) {
	MT.Script.call(this, app, "PageView.mt");
};

CountItOutProject.PageView.prototype = new MT.Script;

CountItOutProject.PageView.prototype.call = function() {
	//run: PageView.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.pageView = function() {
	return new CountItOutProject.PageView(this);
};

/*** script -- TwoCounterOneGroup ***/
CountItOutProject.TwoCounterOneGroup = function(app) {
	MT.Script.call(this, app, "TwoCounterOneGroup.mt");
};

CountItOutProject.TwoCounterOneGroup.prototype = new MT.Script;

CountItOutProject.TwoCounterOneGroup.prototype.call = function() {
	//run: TwoCounterOneGroup.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.twoCounterOneGroup = function() {
	return new CountItOutProject.TwoCounterOneGroup(this);
};

