/***** DO NOT EDIT THIS FILE *****/
// CountItOutProject.js generated by MonkeyTalk at 2012-12-31 14:06:34 PST

load("libs/MonkeyTalkAPI.js");


var CountItOutProject = {};

/*** script -- AnotherTest ***/
CountItOutProject.AnotherTest = function(app) {
	MT.Script.call(this, app, "AnotherTest.mt");
};

CountItOutProject.AnotherTest.prototype = new MT.Script;

CountItOutProject.AnotherTest.prototype.call = function() {
	//run: AnotherTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.anotherTest = function() {
	return new CountItOutProject.AnotherTest(this);
};

/*** script -- CountDownBasic ***/
CountItOutProject.CountDownBasic = function(app) {
	MT.Script.call(this, app, "CountDownBasic.mt");
};

CountItOutProject.CountDownBasic.prototype = new MT.Script;

CountItOutProject.CountDownBasic.prototype.call = function() {
	//run: CountDownBasic.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.countDownBasic = function() {
	return new CountItOutProject.CountDownBasic(this);
};

/*** script -- CountUpBasic ***/
CountItOutProject.CountUpBasic = function(app) {
	MT.Script.call(this, app, "CountUpBasic.mt");
};

CountItOutProject.CountUpBasic.prototype = new MT.Script;

CountItOutProject.CountUpBasic.prototype.call = function() {
	//run: CountUpBasic.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.countUpBasic = function() {
	return new CountItOutProject.CountUpBasic(this);
};

/*** script -- InitialView ***/
CountItOutProject.InitialView = function(app) {
	MT.Script.call(this, app, "InitialView.mt");
};

CountItOutProject.InitialView.prototype = new MT.Script;

CountItOutProject.InitialView.prototype.call = function() {
	//run: InitialView.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.initialView = function() {
	return new CountItOutProject.InitialView(this);
};

/*** script -- PageView ***/
CountItOutProject.PageView = function(app) {
	MT.Script.call(this, app, "PageView.mt");
};

CountItOutProject.PageView.prototype = new MT.Script;

CountItOutProject.PageView.prototype.call = function() {
	//run: PageView.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.pageView = function() {
	return new CountItOutProject.PageView(this);
};

