Test InitialView.mt Run
Test CountUpBasic.mt Run
Test AnotherTest.mt Run
Test CountDownBasic.mt Run
Test FinalView.mt Run
Test DecrementTest.mt Run
Test DeletesTest.mt Run
Test TwoCounterOneGroup.mt Run
Test InitialView.mt Run
